# Generated by Django 5.0.2 on 2024-02-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_author_post_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
