# Generated by Django 5.0.2 on 2024-02-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_post_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
